sudo: required
services:
    - docker
before_install:
    - docker build -t gokulsubramani/docker-angular -f Dockerfile.dev .
install:
     - npm install -g @angular/cli@latest
     - npm install
script:
     - docker run -t gokulsubramani/docker-angular npm run start --coverage
    