sudo: required
services:
    - docker
before_install:
    - docker build -t gokulsubramani/docker-angular -f Dockerfile.dev .
angular_karma:
    image: alpine/ng-cli-karma:latest
    container_name: 'angular_karma'
    volumes:
        - .:/app/
    working_dir: /app/
    ports:
        - 9876:9876
    command: >
          bash -c "ng test"
script:
    - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
    #- docker run -t gokulsubramani/docker-angular -p "4200:4200" npm run start