sudo: required
services:
    - docker
before_install:
    - npm install -g @angular/cli
    - docker build -t gokulsubramani/docker-angular -f Dockerfile.dev .
install:
    - npm ci
script:
    - ng test --watch=false
    - docker run gokulsubramani/docker-angular ng test