sudo: required
dist: trusty
language: node_js
node_js:
  - '12.0'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t gokulsubramani/docker-angular -f Dockerfile.dev .

before_script:
- npm install

script: 
- npm run test -- --watch=false --code-coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "EBSDocker"
    env: "DockeEbsDockerrAngular-env"
    bucket_name: "elasticbeanstalk-ap-south-1-914520140918"
    bucket_path: "EBSDocker"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY